### ISSUE TITLE
question: setup CUDA support for sherpa-onnx on Windows using conda

### ISSUE THREAD

**Issue by mokurin000** [Open-LLM-VTuber/Open-LLM-VTuber#112]
1. sherpa-onnx from https://k2-fsa.github.io/sherpa/onnx/cuda.html were bundled with onnxruntime*.dll targetting CUDA 11.x, they provides no documentation explaining CUDA version of their prebuilt-binaries.
```bash
pixi run python -m pip install sherpa-onnx==1.0.41+cuda -f https://k2-fsa.github.io/sherpa/onnx/cuda.html
```
2. Is CUDAProvider check for onnxruntime needed to run sherpa-onnx on CUDA? Sherpa-onnx bundled their onnxruntime cuda provider to site-packages/ (`onnxruntime_providers_cuda.dl`)
3. Building `sherpa-onnx` with Visual Studio 2022, `nvidia::cuda-toolkit==12.6` and `nvidia::cudnn==9.3.0` will fail with:> CMake is installed via scoop, I will try cmake from Microsoft C++ BuildTools later
```text
> pixi run python setup.py install
-- Building for: Visual Studio 15 2017 Win64
CMake Error at CMakeLists.txt:8 (project):
  Generator

    Visual Studio 15 2017 Win64

  could not find any instance of Visual Studio.
```
4. using pre-built sherpa-onnx, `conda-forge::cudatoolkit==11.8` and `conda-forge::cudnn<8.8`, it will raise RuntimeError, though all needed DLL's are installed:
```text
RuntimeError: D:\a\_work\1\s\onnxruntime\core\session\provider_bridge_ort.cc:1209 onnxruntime::ProviderLibrary::Get [ONNXRuntimeError] : 1 : FAIL : LoadLibrary failed with error 1114 "" when trying to load "C:\Users\moku\Repos\Open-LLM-VTuber\.pixi\envs\default\Lib\site-packages\onnxruntime_providers_cuda.dll"
```

```text
Microsoft (R) COFF/PE Dumper Version 14.42.34436.0
Copyright (C) Microsoft Corporation.  All rights reserved.

Dump of file C:\Users\moku\Repos\Open-LLM-VTuber\.pixi\envs\default\Lib\site-packages\onnxruntime_providers_cuda.dll

File Type: DLL

  Section contains the following imports:

    cublasLt64_11.dll
    cublas64_11.dll
    cudnn64_8.dll
    cufft64_10.dll
    cudart64_110.dll
 ```

> Using sherpa-onnx with CPU works out-of-the-box, but it has too high latency

**Comment by mokurin000** [comment]
4. With instructions from our guide,

I installed CUDA Toolkit 11.8 via officiial installer,
extracted CUDNN v8.9 to "C:\Program Files\NVIDIA\CUDNN\v8.9\"

```nushell
uv remove sherpa-onnx onnxruntime
uv add onnxruntime-gpu sherpa-onnx==1.10.39+cuda -f https://k2-fsa.github.io/sherpa/onnx/cuda.html 
$env.PATH = ( $env.PATH | append 'C:\Program Files\NVIDIA\CUDNN\v8.9\bin')
uv run .\run_server.py
```

just still not working

**Comment by mokurin000** [comment]
thanks to @csukuangfj, I get the problem figured out

Since pre-built cuda wheels from `sherpa-onnx` were bundled with onnxruntime.dll for onnxruntime `1.17.1`, thus, we:
 - should not install `onnxruntime`
 - should not install `onnxruntime-gpu` with version other than `1.17.1`

So with a `pixi.toml`:

```toml
[project]
authors = ["mokurin000 <1348292515a@gmail.com>"]
channels = ["conda-forge"]
description = "Add a short description here"
name = "Open-LLM-VTuber"
platforms = ["win-64"]
version = "0.1.0"

[tasks]

# removed faster-whisper as it will introduce `onnxruntime` 
[pypi-dependencies]
anthropic = ">=0.40.0"
azure-cognitiveservices-speech = ">=1.41.1"
chardet = ">=5.2.0"
edge-tts = ">=7.0.0"
fastapi = ">=0.115.6"
groq = ">=0.13.0"
httpx = ">=0.28.1"
langdetect = ">=1.0.9"
loguru = ">=0.7.2"
numpy = ">=1.26.4,<2"
openai = ">=1.57.4"
pydub = ">=0.25.1"
pysbd = ">=0.3.4"
pyttsx3 = ">=2.98"
pyyaml = ">=6.0.2"
requests = ">=2.32.3"
ruff = ">=0.8.6"
scipy = ">=1.14.1"
soundfile = ">=0.12.1"
tomli = ">=2.2.1"
tqdm = ">=4.67.1"
websocket-client = ">=1.8.0"
uvicorn = { version = ">=0.34.0, <0.35", extras = ["standard"] }
pip = ">=25.0, <26"
onnxruntime-gpu = "==1.17.1"

[dependencies]
python = "<3.13"
cudatoolkit = { version = "==11.8", channel = "conda-forge" }
cudnn = { version = "<9", channel = "conda-forge" }
```

And run:

```nushell
pixi run python -m pip install sherpa-onnx==1.10.39+cuda -f https://k2-fsa.github.io/sherpa/onnx/cuda.html
```

CUDA-accelerated sherpa_onnx_tts will work fine!
